In [2]:
import numpy as np 

In [3]:
arr = np.array([1,3,4])    #from list to array

In [4]:
arr

array([1, 3, 4])

In [5]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.full((4,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [8]:
np.eye(5)   #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.arange(1,100,5)       # it give the array of gap 5 from 1 to 100 and 100 in not included till 100-1 or n-1

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [29]:
np.linspace(1,100,5)        # it give evenly spaced array of size 5

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [11]:
myarr = np.array([[1,2,3,3],[2,32,12,11],[4,45,54,56],[9,9,1,0]])

In [12]:
myarr

array([[ 1,  2,  3,  3],
       [ 2, 32, 12, 11],
       [ 4, 45, 54, 56],
       [ 9,  9,  1,  0]])

**numpy array properties**

In [13]:
myarr.shape

(4, 4)

In [14]:
myarr.size

16

In [15]:
myarr.dtype

dtype('int64')

In [16]:
myarr.ndim

2

**changing data type**

In [17]:
myarr = np.array([[1,2,3,3],[2,32,12,11],[4,45,54,56],[9,9,1,0]],dtype = 'float64') #explicityly

In [18]:
myarr

array([[ 1.,  2.,  3.,  3.],
       [ 2., 32., 12., 11.],
       [ 4., 45., 54., 56.],
       [ 9.,  9.,  1.,  0.]])

In [19]:
myarr.dtype

dtype('float64')

In [20]:
n = myarr.astype('int32')  

In [21]:
n.dtype

dtype('int32')

**reshaping and flattering**

In [22]:
myarr = np.array([[1,2,3,3],[2,32,12,11],[4,45,54,56]])

In [23]:
myarr

array([[ 1,  2,  3,  3],
       [ 2, 32, 12, 11],
       [ 4, 45, 54, 56]])

In [24]:
myarr.shape

(3, 4)

In [25]:
reshaped = myarr.reshape((4,3))

In [26]:
reshaped

array([[ 1,  2,  3],
       [ 3,  2, 32],
       [12, 11,  4],
       [45, 54, 56]])

In [27]:
myarr.reshape((6,2))

array([[ 1,  2],
       [ 3,  3],
       [ 2, 32],
       [12, 11],
       [ 4, 45],
       [54, 56]])

In [28]:
myarr.flatten()   #convert 2d element to 1d element && we can convert 1d to 2d usig reshaped

array([ 1,  2,  3,  3,  2, 32, 12, 11,  4, 45, 54, 56])