In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [4]:
flat = arr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [6]:
flat[2]

np.int64(3)

In [7]:
flat[3:8]

array([4, 5, 6, 7, 8])

In [8]:
flat[:4]

array([1, 2, 3, 4])

In [9]:
flat[4:]

array([ 5,  6,  7,  8,  9, 11, 12, 13])

In [10]:
flat[::3]  # Every Third element 

array([ 1,  4,  7, 11])

In [11]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [12]:
b = flat[2:7]

In [13]:
b

array([3, 4, 5, 6, 7])

In [14]:
b[0] = 4444

In [15]:
b

array([4444,    4,    5,    6,    7])

In [16]:
flat   # Here flat also change bcz numpy allocate same memory location for fasten and efficiency it is only view not copy

array([   1,    2, 4444,    4,    5,    6,    7,    8,    9,   11,   12,
         13])

In [17]:
c = flat[3:7].copy()   # Now it is copy not view

In [18]:
c

array([4, 5, 6, 7])

In [19]:
c[0] = 444666

In [20]:
c

array([444666,      5,      6,      7])

In [21]:
flat

array([   1,    2, 4444,    4,    5,    6,    7,    8,    9,   11,   12,
         13])

In [22]:
arr = np.array([1,54,23,53,2,3,34,5,6])

In [23]:
arr

array([ 1, 54, 23, 53,  2,  3, 34,  5,  6])

In [25]:
arr[[1,4,6]]  #fancy indexing (select multiple elements)

array([54,  2, 34])

In [45]:
arr[arr>3]  #boolean masking (filter data)

array([4, 5, 6])

In [28]:
array = np.array([[1,3,4],[4,5,7],[8,9,0]])

In [29]:
array

array([[1, 3, 4],
       [4, 5, 7],
       [8, 9, 0]])

In [31]:
array.shape

(3, 3)

In [37]:
x = np.array([1.1,2.2,3.3],dtype ='int32')

In [38]:
x

array([1, 2, 3], dtype=int32)

In [39]:
arr = np.array([1,2,3,4,5,6])

In [40]:
arr

array([1, 2, 3, 4, 5, 6])

In [41]:
arr[[1,3,5]]

array([2, 4, 6])

In [42]:
y = np.array([[56,45,76],[43,45,90]])

In [43]:
y

array([[56, 45, 76],
       [43, 45, 90]])

In [46]:
y[y>50]

array([56, 76, 90])

In [48]:
z = np.array([1,2,3,4,5,6,7,8,9])

In [49]:
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
z.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])