In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
result = arr ** 2  #vectorization operation
print(result)


[ 1  4  9 16 25]


In [7]:
result + 10          #broadcast ()

array([21, 32, 43])

In [8]:
arr1 = np.array([1,2,3])
arr2= np.array([10,20,30])
resultt = arr1 + arr2

In [9]:
resultt

array([11, 22, 33])

In [11]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr1d = np.array([1,2,3])
ans = arr2d + arr1d

In [12]:
ans

array([[2, 4, 6],
       [5, 7, 9]])

In [13]:
data = np.array([[10,20,30],
                 [15,25,35],
                 [20,30,40],
                 [25,35,45],
                 [30,40,50]])

In [16]:
mean = data.mean(axis = 0)
mean

array([20., 30., 40.])

In [17]:
std = data.std(axis=0)
std

array([7.07106781, 7.07106781, 7.07106781])