In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [4]:
flat = arr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [6]:
flat[2]

np.int64(3)

In [7]:
flat[3:8]

array([4, 5, 6, 7, 8])

In [8]:
flat[:4]

array([1, 2, 3, 4])

In [9]:
flat[4:]

array([ 5,  6,  7,  8,  9, 11, 12, 13])

In [10]:
flat[::3]  # Every Third element 

array([ 1,  4,  7, 11])

In [11]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [12]:
b = flat[2:7]

In [13]:
b

array([3, 4, 5, 6, 7])

In [14]:
b[0] = 4444

In [15]:
b

array([4444,    4,    5,    6,    7])

In [16]:
flat   # Here flat also change bcz numpy allocate same memory location for fasten and efficiency it is only view not copy

array([   1,    2, 4444,    4,    5,    6,    7,    8,    9,   11,   12,
         13])

In [17]:
c = flat[3:7].copy()   # Now it is copy not view

In [18]:
c

array([4, 5, 6, 7])

In [19]:
c[0] = 444666

In [20]:
c

array([444666,      5,      6,      7])

In [21]:
flat

array([   1,    2, 4444,    4,    5,    6,    7,    8,    9,   11,   12,
         13])