In [1]:
import numpy as np


In [2]:
arr = np.array([3,4,2,33])

In [3]:
arr

array([ 3,  4,  2, 33])

In [4]:
np.mean(arr)

np.float64(10.5)

In [5]:
np.min(arr)

np.int64(2)

In [6]:
np.max(arr)

np.int64(33)

In [7]:
np.std(arr)

np.float64(13.009611831257688)

In [8]:
np.var(arr)

np.float64(169.25)

In [9]:
np.sum(arr)

np.int64(42)

In [11]:
np.prod(arr)

np.int64(792)

In [12]:
np.percentile(arr,50)

np.float64(3.5)

In [13]:
np.argmin(arr)  #gives minimmum element index

np.int64(2)

In [14]:
np.argmax(arr)

np.int64(3)

In [15]:
np.median(arr)

np.float64(3.5)

In [16]:
arr2 = np.array([43,56,87,90])

In [17]:
np.corrcoef(arr,arr2)

array([[1.        , 0.57374584],
       [0.57374584, 1.        ]])

In [18]:
np.unique(arr)  #find unique element in array

array([ 2,  3,  4, 33])

In [19]:
np.diff(arr)  #compute nth difference of an array

array([ 1, -2, 31])

In [20]:
np.cumsum(arr)  #calculate cumulative sum of an array

array([ 3,  7,  9, 42])

In [21]:
np.linspace(0,10,5)   #Create an array with evenly spaced numbers over a specified interval.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.log(arr)  #compute the natural logarithm of an rray

array([1.09861229, 1.38629436, 0.69314718, 3.49650756])

In [23]:
np.exp(arr)   #compute the exponential of an array

array([2.00855369e+01, 5.45981500e+01, 7.38905610e+00, 2.14643580e+14])